modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="suppressionmod"
version="1.0.0"
displayName="Suppression Mod"
description="Реалистичное подавление от пуль TaCZ с накоплением эффекта"
authors="liko"

[[dependencies.suppressionmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.suppressionmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
